CC ?= cc
CFLAGS ?= -O2 -g -std=gnu89 -Wall -Wextra
CPPFLAGS += -DNeXT -DNeXT_MOD -DNeXT_NFS -Iinclude
SCRATCH_DIR = $(CURDIR)/.scratch
MKFS_BIN = mkfs.nextufs
export TMPDIR = $(SCRATCH_DIR)

.PHONY: all clean scratch-dir

all: scratch-dir $(MKFS_BIN)

scratch-dir:
	mkdir -p $(SCRATCH_DIR)

$(MKFS_BIN): mkfs.o
	$(CC) $(CFLAGS) -o $@ mkfs.o

mkfs.o: mkfs.c
	$(CC) $(CPPFLAGS) $(CFLAGS) -c -o $@ mkfs.c

clean:
	rm -f mkfs.o $(MKFS_BIN) mkfs_next
