CC = cc
CFLAGS = -O2 -g -std=gnu99 -Wall -Wextra -Werror
CPPFLAGS = -I../nextufs
BIN = nextufs.resize
SRCS = nextufs_resize.c
OBJS = $(SRCS:.c=.o)

.PHONY: all clean test

all: $(BIN)

$(BIN): $(OBJS) ../nextufs/libnextufs.a
	$(CC) $(CFLAGS) -o $@ $(OBJS) ../nextufs/libnextufs.a

nextufs_resize.o: nextufs_resize.c
	$(CC) $(CPPFLAGS) $(CFLAGS) -c -o $@ $<

../nextufs/libnextufs.a:
	$(MAKE) -C ../nextufs -f Makefile.linux libnextufs.a

clean:
	rm -f $(BIN) $(OBJS)

test: all
	./$(BIN) --help >/dev/null
